### ISSUE TITLE
Valore del delay del protobuffer non settato

### ISSUE THREAD

**Issue by paolotoldo** [Alebat/SensorsFlows#1]
Nel costruttore del protobuffer hai come parametro il valore del delay, ma non l'hai passato alla variabile interna, ecco come dovrebbe essere invece il costruttore, correggemi se sbaglio

public ProtobufferOutput(String name, File dir, long flushSizeElements, String phoneId, int timeOffsetMillis, Dictionary<Class, SensorInfo.TYPESENSOR> sensorTypesMap) { // TODO Horrible
        mName = name;
        mFolder = dir;
        mFlushSize = flushSizeElements;
        uuid = phoneId;
        uid = UUID.randomUUID();
        mTypesMap = sensorTypesMap;
        mTimeOffsetMillis = timeOffsetMillis;
    }

**Comment by Alebat** [comment]
@paolotoldo Risolvo appena possibile, con "Horrible" invece cosa intendi?

**Comment by paolotoldo** [comment]
Ottimo.
Per l'Horrible... Non guardare me, e' un tuo commento, che ho ricopiato.

**Comment by Alebat** [comment]
@paolotoldo Aaah, si il motivo c'era!

**Comment by Alebat** [comment]
Fatto, tu usi il costruttore principalmente per passarlo?
Chiudila pure tu l'issue
