### ISSUE TITLE
EXLs3Device.java, java.lang.ArithmeticException: divide by zero

### ISSUE THREAD

**Issue by paolotoldo** [Alebat/SensorsFlows#2]
Possibile soluzione, controllare il valore:

```
 if(parent.qDS!=0)
                    if (parent.on.streaming && (qd++ % parent.qDS) == 0)
                        parent.on.sensorValue(now, new double[]{p.q1, p.q2, p.q3, p.q4});
                if(parent.bDS!=0)
                    if (parent.ry.streaming && (bd++ % parent.bDS) == 0)
                        parent.ry.sensorValue(now, new double[]{p.vbatt});
```

**Comment by Alebat** [comment]
@paolotoldo Cosa passi come frequenza di downsampling/decimation?

**Comment by paolotoldo** [comment]
Ho visto meglio adesso. Non avevo guardato il codice, ma preso e adattato il tuo esempio. E' quello da correggere allora). Che valore impostiamo allora?

**Comment by Alebat** [comment]
Non 0, 1 se vuoi tutti i sample, se no x cioè 1 ogni x. La batteria ad esempio 100 cioè 1hz il quaternione non saprei intanto lascia pure 1.

**Comment by paolotoldo** [comment]
ho messo 20 intanto. Tu correggi esempio. grazie
